### ISSUE TITLE
Crisp is not working in my Shopify store

### ISSUE THREAD

**Issue by agheravivek** [SatelCreative/crisp#7]
Hi,

Hope you doing well!!!
I like the code example which you added into GitHub and I tried to add it into my Shopify store. But somehow it is not working.
GitHub Link: https://github.com/SatelCreative/crisp
So, can you please help me here that which step I'm missing to working your code in my Shopify store?

Thanks.

**Comment by qw-in** [comment]
Can you please provide more details about the issue?

**Comment by agheravivek** [comment]
Hello,
I want to apply this filter demo in my Shopify store Demo URL: https://flowparts.com/collections/all
So which steps I need to follow.
Please help me.

**Comment by agheravivek** [comment]
> Can you please provide more details about the issue?

Hello, can you please help us?

**Comment by qw-in** [comment]
Sorry, we provide the library and documentation for free but it is up to you to implement. If you find specific bugs or have specific questions about the documentation happy to help.

**Comment by agheravivek** [comment]
Hello,
Thanks for your reply.
can you please just let me know for that filter layout which steps I need to follow? so, I can try it out again myself.
hope you help me.
Thanks.
