### ISSUE TITLE
risp is not working in my Shopify store

### ISSUE THREAD

**Issue by agheravivek** [SatelCreative/crisp#8]
Hi,

Hope you doing well!!!
I like the code example which you added into GitHub and I tried to add it into my Shopify store. But somehow it is not working.
GitHub Link: https://github.com/SatelCreative/crisp
So, can you please help me here that which step I'm missing to working your code in my Shopify store?

Thanks.

**Comment by qw-in** [comment]
Please don't open duplicate issues
