### ISSUE TITLE
Please help me to understand some code

### ISSUE THREAD

**Issue by Ajay8444** [SatelCreative/crisp#9]
Hello,

  I'm trying to use this library but I'm stuck. Can you please help me to understand how to filter function work with the collection filtering and how data appears?

Thank you

**Comment by qw-in** [comment]
Hi @Ajay8444, I'd be happy to answer specific questions but I'm going to have to point you to the documentation. If there is something in the documentation isn't clear on or doesn't cover feel free to ask for clarification. Thanks
